### ISSUE TITLE
[Bug]: Configuration file missing in 1.21+

### ISSUE THREAD

**Issue by ZelestialRexPig** [Fuzss/blockrunner#21]
### Mod Loader (Required)

Fabric

### Minecraft Version(s) (Required)

1.21.1

### Mod Version(s) (Required)

21.1.0

### Other Mods Involved (Required)

Yes

### Notes (Required)

The config file for added new blocks to have speed values is not generating. I manually put one it and it didn't load it. Basically the config is broken.

### latest.log (Required)

<script src="https://gist.github.com/ZelestialRexPig/eb92e7dd9725b7a4edbc64d142855182.js"></script>

**Comment by ZelestialRexPig** [comment]
I messed up the gist but here is the log

https://gist.github.com/ZelestialRexPig/2866f9f924dee240251af067d1662cb0

**Comment by Fuzss** [comment]
Thanks for reporting! Configuration has changed for 1.21+, I updated the [README](https://github.com/Fuzss/blockrunner/blob/main/README.md).

**Comment by ZelestialRexPig** [comment]
Oh thank you! This helps a lot :D

**Comment by quantumgolem** [comment]
@Fuzss I tried setting custom block speeds using the data map but couldn’t get it to work. I created the `blockrunner` folder and copied the folder map that's described in the README inside the `.minecraft/data` folder since the `blockrunner` folder didn't already exist there. I then added the following `block_speeds.json` file:

```
{
  "values": {
    "minecraft:dirt_path": {
      "speed": 3.0
    },
    "minecraft:spruce_planks": {
      "speed": 3.0
    }
  }
}
```

Running `/reload` doesn’t seem to do anything (it just says "Reloading!"), so I had to restart the game, but even after restarting, the custom speeds don’t seem to apply. I can't even see the tooltips. The mod definitely works though since I get faster speeds on dirt. Am I missing something? I’m on macOS, by the way.

**Comment by quantumgolem** [comment]
@ZelestialRexPig Can I ask you how you got it to work? The README doesn't really explain what files to create, it just says something about a data map without explanation of how to create it, so I might be doing something wrong.

**Comment by Fuzss** [comment]
https://github.com/Fuzss/blockrunner/blob/main/1.21.1/Common/src/generated/resources/data/blockrunner/data_maps/block/block_speeds.json

**Comment by VTCruzer** [comment]
> [@ZelestialRexPig](https://github.com/ZelestialRexPig) Can I ask you how you got it to work? The README doesn't really explain what files to create, it just says something about a data map without explanation of how to create it, so I might be doing something wrong.

Did you ever figure this out? I tried going here https://github.com/Fuzss/neoforgedatapackextensions like the author has linked before and I couldn't figure out what to do. There's no mod to download or any clear instructions on how these data map things work.

**Comment by CosmicQuail** [comment]
This thread hasn't helped at all. I am trying to figure out how to add config for custom blocks and none of the links in this thread have provided any assistance. I have followed the same steps as quantumgolem and copied pasted the exact text in Fuzss' last link  into a block_speeds json file and put in the exact example from the readme with replacing the block name and it does not work at all. Whatever was going on in the 1.20.4 and previous versions' config file seemed infinitely easier to add custom block speed than whatever folders i have to create with a data > blockrunner > data_maps > block > block_speeds.json system that has 0 explanation or support. What even is a data map.

**Comment by Fuzss** [comment]
See: https://docs.neoforged.net/docs/resources/server/datamaps/
For additional help please visit #fuzs-projects: https://lunapixel.studio/discord

**Comment by FlorianFreudiger** [comment]
The way to do it is through a custom data-pack.
https://minecraft.wiki/w/Tutorial:Creating_a_data_pack
In the data-pack you can then create a `data/blockrunner/data_maps/block/block_speeds.json` file and fill it accordingly, you can also overwrite the existing tags, [in the same way they are defined](https://github.com/Fuzss/blockrunner/blob/228557f3670c879cb38f403e4ac6d4090daff04e/1.21.4/Common/src/generated/resources/data/blockrunner/data_maps/block/block_speeds.json)

Here's an example data-pack to demonstrate, you can also just unpack, modify, repack that.
[BlockRunner-CustomConfig.zip](https://github.com/user-attachments/files/18815363/BlockRunner-CustomConfig.zip)
In that I set the speed of `minecraft:dirt` and overwrite the speed of the `#blockrunner:quick_blocks` tag (only contains `minecraft:dirt_path` currently). Speed has to be in range 0.0 to 8.0.

You will also need to enable the data-pack when creating a new save or use a mod like these:
- https://modrinth.com/mod/datapack-injector (only works on servers in my experience)
- https://modrinth.com/mod/datapacks


But I agree it's pretty cumbersome to do all that instead of having a simple config file...

Hope that helps! 🙂

**Comment by quantumgolem** [comment]
@FlorianFreudiger Thanks so much. Back when I used this mod, I couldn't for the life of me figure out how to get it working. I thought that it would be a config file. This will come in handy if I ever decide to figure out how to get this working again.
